apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptimekuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:luismartorano/uptimekumaargocd.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: uptimekuma
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true