apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptimekuma-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/var/lib/uptimekuma"  # <-- Novo caminho
